mail_search:
  path: /mail/search
  methods: GET
  defaults: { _controller: Evrinoma\EximBundle\Controller\EximController::mailSearch}
  options:
    expose: true

mail_domain:
  path: /mail/domain
  methods: GET
  defaults: { _controller: Evrinoma\EximBundle\Controller\EximController::mailDomain}
  options:
    expose: true

mail_acl:
  path: /mail/acl
  methods: GET
  defaults: { _controller: Evrinoma\EximBundle\Controller\EximController::mailAcl}
  options:
    expose: true
